[default]
locale = "en-gb"

[default.extend-words]
color = "color"
colors = "colors"
center = "center"
acces = "acces"
itemize = "itemize"
initialy = "initialy"
uncolored = "uncolored"
miter = "miter"
Beeing = "Beeing"
Mis = "Mis"
Arbor = "Arbor"
artifact =  "artifact"
dolor = "dolor"

[files]
extend-exclude = ["*.svg", "LICENSE.txt", "BusyPanda.sty", "BusyPanda_fonts_lualatex.dat", "BusyPanda_fonts_pdflatex.dat", "BusyPanda_fonttest.tex", "BusyPanda_test.tex"]
ignore-vcs = true